name: Build CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build CI with Node ${{ matrix.node-version }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version:
          - 24.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use Pnpm
        uses: pnpm/action-setup@v6

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate Formatting
        run: pnpm run prettier:check

      - name: Validate Locale
        run: pnpm run check:locale

      - name: Lint Extension
        run: pnpm run lint

      - name: Build Extension
        run: pnpm run build

      - name: Prepare Test Runner
        run: |
          sudo apt-get install meson gjs gir1.2-gda-5.0 gir1.2-gsound-1.0 -y
          git clone --depth=1 https://github.com/ptomato/jasmine-gjs
          cd jasmine-gjs
          meson setup build
          meson compile -C build
          sudo meson install -C build

      - name: Run Tests
        run: pnpm run test
